[workspace]
members = [
  "contracts/address-provider",
  "contracts/incentives",
  "contracts/oracle/*",
  "contracts/params",
  "contracts/swapper/*",
  "contracts/red-bank",
  "contracts/rewards-collector",
  "packages/chains/*",
  "packages/health",
  "packages/testing",
  "packages/types",
  "packages/utils",
  "packages/mars-swapper",
  "integration-tests",
]

[workspace.package]
version = "1.0.1"
authors       = [
  "Gabe R. <gabe.r@delphilabs.io>",
  "Larry Engineer <larry@delphidigital.io>",
  "Piotr Babel <piotr@delphilabs.io>",
  "Spike Spiegel <spikeonmars@protonmail.com>",
  "Brianna M. <brianna@delphilabs.io>",
  "Ahmad Kaouk",
  "Harry Scholes",
]
edition = "2021"
license = "GPL-3.0-or-later"
repository = "https://github.com/mars-protocol/red-bank"
homepage = "https://marsprotocol.io"
documentation = "https://docs.marsprotocol.io/"
keywords = [
  "mars",
  "cosmos",
  "cosmwasm",
]

[workspace.dependencies]
anyhow            = "1.0.68"
bech32            = "0.9.1"
cosmwasm-schema   = "1.1.9"
cosmwasm-std      = "1.1.9"
cw2               = { git = "https://github.com/mars-protocol/cw-plus", rev = "4014255" }
cw-multi-test     = "0.16.1"
cw-storage-plus   = "1.0.1"
cw-utils          = "1.0.1"
mars-owner        = { version = "1.0.0", features = ["emergency-owner"] }
osmosis-std       = "0.14.0"
osmosis-test-tube = "15.1.0"
prost             = { version = "0.11.5", default-features = false, features = ["prost-derive"] }
schemars          = "0.8.11"
serde             = { version = "1.0.152", default-features = false, features = ["derive"] }
thiserror         = "1.0.38"
pyth-sdk-cw        = "1.0.0"
cw-paginate       = "0.2.1"
astroport         = { git = "https://github.com/astroport-fi/astroport-core", tag = "v2.7.1" }
strum             = "0.24.1"

# dev-dependencies
cw-it             = { git = "https://github.com/apollodao/cw-it.git", rev = "2d59e15703aaa377cfb09f0e021b3b63bc827a22" }
test-case         = "3.0.0"
proptest          = "1.1.0"

# packages
mars-health         = { version = "1.0.0", path = "./packages/health" }
mars-osmosis        = { version = "1.0.0", path = "./packages/chains/osmosis" }
mars-red-bank-types = { version = "1.0.0", path = "./packages/types" }
mars-testing        = { version = "1.0.0", path = "./packages/testing" }
mars-utils          = { version = "1.0.0", path = "./packages/utils" }
mars-swapper        = { version = "1.0.0", path = "./packages/mars-swapper" }

# contracts
mars-address-provider          = { version = "1.0.0", path = "./contracts/address-provider" }
mars-incentives                = { version = "1.0.0", path = "./contracts/incentives" }
mars-oracle-base               = { version = "1.0.0", path = "./contracts/oracle/base" }
mars-oracle-osmosis            = { version = "1.0.0", path = "./contracts/oracle/osmosis" }
mars-oracle-wasm               = { version = "1.0.0", path = "./contracts/oracle/wasm" }
mars-red-bank                  = { version = "1.0.0", path = "./contracts/red-bank" }
mars-rewards-collector         = { version = "1.0.0", path = "./contracts/rewards-collector" }
mars-swapper-base              = { version = "1.0.0", path = "./contracts/swapper/base" }
mars-swapper-astroport         = { version = "1.0.0", path = "./contracts/swapper/astroport" }
mars-swapper-osmosis           = { version = "1.0.0", path = "./contracts/swapper/osmosis" }

[profile.release]
codegen-units    = 1
debug            = false
debug-assertions = false
incremental      = false
lto              = true
overflow-checks  = true
opt-level        = 3
panic            = "abort"
rpath            = false
