[workspace]
members = [
  "contracts/swapper/*",
  "contracts/params",
  "packages/*"
]

[workspace.package]
version       = "1.0.5"
authors       = [
  "Gabe R. <gabe.r@delphilabs.io>",
  "Larry Engineer <larry@delphidigital.io>",
  "Piotr Babel <piotr@delphilabs.io>",
  "Brianna M. <brianna@delphilabs.io>"
]
license       = "GPL-3.0-or-later"
edition       = "2021"
repository    = "https://github.com/mars-protocol/mars-common"
homepage      = "https://marsprotocol.io"
documentation = "https://docs.marsprotocol.io/"
keywords      = ["mars", "cosmos", "cosmwasm"]

[workspace.dependencies]
anyhow             = "1.0.71"
cosmwasm-schema    = "1.2.6"
cosmwasm-std       = "1.2.6"
cw2                = "1.0.1"
cw-multi-test      = "0.16.5"
cw-paginate        = "0.2.1"
cw-storage-plus    = "1.0.1"
osmosis-std        = "0.15.3"
osmosis-test-tube  = "15.1.0"
schemars           = "0.8.12"
serde              = { version = "1.0.164", default-features = false, features = ["derive"] }
thiserror          = "1.0.40"

# packages
mars-osmosis               = { git = "https://github.com/mars-protocol/red-bank", rev = "00301d60c38af09d8eb7980355009e2f00c6f41f" }
mars-owner                 = { version = "1.2.0", features = ["emergency-owner"] }
mars-swapper               = { path = "packages/mars-swapper" }
mars-utils                 = "1.0.0"

# contracts
mars-swapper-base = { version = "1.0.0", path = "contracts/swapper/base" }

[profile.release]
codegen-units    = 1
debug            = false
debug-assertions = false
incremental      = false
lto              = true
overflow-checks  = true
opt-level        = 3
panic            = "abort"
rpath            = false
